//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTheHand.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InTheHand.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish connection to network..
        /// </summary>
        internal static string net_could_not_connect {
            get {
                return ResourceManager.GetString("net_could_not_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method names cannot be null or empty..
        /// </summary>
        internal static string net_invalid_method_name {
            get {
                return ResourceManager.GetString("net_invalid_method_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-CLS Compliant Exception (i.e. an object that does not derive from System.Exception) was thrown..
        /// </summary>
        internal static string net_nonClsCompliantException {
            get {
                return ResourceManager.GetString("net_nonClsCompliantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed after the request has been submitted..
        /// </summary>
        internal static string net_reqsubmitted {
            get {
                return ResourceManager.GetString("net_reqsubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not supported..
        /// </summary>
        internal static string net_unsupported_method {
            get {
                return ResourceManager.GetString("net_unsupported_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred during a WebClient request..
        /// </summary>
        internal static string net_webclient {
            get {
                return ResourceManager.GetString("net_webclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not a valid base address..
        /// </summary>
        internal static string net_webclient_invalid_baseaddress {
            get {
                return ResourceManager.GetString("net_webclient_invalid_baseaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebClient does not support concurrent I/O operations..
        /// </summary>
        internal static string net_webclient_no_concurrent_io_allowed {
            get {
                return ResourceManager.GetString("net_webclient_no_concurrent_io_allowed", resourceCulture);
            }
        }
    }
}
